[build]
command = "npm run build:only"
publish = "dist"

[build.environment]
NODE_VERSION = "18.20.5"
NODE_OPTIONS = "--max-old-space-size=8192"

[[headers]]
for = "/_astro/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[functions]
node_bundler = "esbuild"
directory = ".netlify/functions-internal"
included_files = ["dist/**/*"]

[functions.ssr]
external_node_modules = ["@astrojs/netlify", "square"]