[build]
command = "npm run build"
publish = "dist"
functions = ".netlify/functions"

[build.environment]
NODE_VERSION = "18.20.5"

[[redirects]]
from = "/*"
to = "/.netlify/functions/entry-server"
status = 200
force = true

[functions]
external_node_modules = ["@astrojs/*"]
included_files = ["dist/**/*"]

[[headers]]
for = "/_astro/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"