[build]
command = "pnpm run build"
publish = "dist"
functions = "netlify/functions"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Content-Security-Policy = "frame-ancestors 'none'"

[build.environment]
NODE_VERSION = "18"

[dev]
command = "pnpm run dev"
targetPort = 4321
port = 8888
framework = "astro"