[build]
command = "npm run build:only"
publish = "dist"

[build.environment]
NODE_VERSION = "18.20.5"
NODE_OPTIONS = "--max-old-space-size=8192"
DATABASE_PATH = "/var/data"

[[redirects]]
from = "/api/*"
to = "/netlify/functions/payload/:splat"
status = 200

[[redirects]]
from = "/media/*"
to = "/netlify/functions/payload/media/:splat"
status = 200

[functions]
node_bundler = "esbuild"
directory = "netlify/functions"
included_files = [
  "cms/src/collections/**/*",
  "cms/src/payload.config.ts",
  "src/lib/payload/module.d.ts"
]

[functions.payload]
external_node_modules = [
  "@payloadcms/db-sqlite",
  "better-sqlite3",
  "payload",
  "express"
]