[build]
command = "npm run build"
publish = "dist"
functions = ".netlify/edge-functions"

[build.environment]
NODE_VERSION = "18.20.5"

[[redirects]]
force = true
from = "/*"
status = 200
to = "/.netlify/functions/entry-server"

[functions]
included_files = ["dist/**/*"]

[[headers]]
for = "/_astro/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[dev]
framework = "astro"
targetPort = 4321