[build]
command = "pnpm run build"
publish = "dist"
# functions = "netlify/functions"  # Not currently using serverless functions

# === PHASE 4: ENHANCED NETLIFY IMAGE CDN CONFIGURATION ===
# Enable automatic format conversion (AVIF/WebP) for ALL external images
# Phase 4 Enhancement: Broader WordPress patterns + quality optimization
# Expected: Additional 15-25% LCP improvement on article pages
[images]
remote_images = [
  "https://.*\\.squarecdn\\.com/.*",
  "https://.*\\.s3\\..*\\.amazonaws\\.com/.*",
  "https://.*\\.wordpress\\.com/.*",
  "https://i[0-9]\\.wp\\.com/.*",
  "https://.*\\.wp\\.com/.*",           # Broader WordPress.com pattern
  "https://secure\\.gravatar\\.com/.*"  # Gravatar avatars
]

# Root page - HTTP/2 Push for critical assets
[[headers]]
for = "/"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"
Link = '''</fonts/AlumniSans.woff2>; rel=preload; as=font; type=font/woff2; crossorigin,
</fonts/Cabin.woff2>; rel=preload; as=font; type=font/woff2; crossorigin'''

# HTML files - short cache, always revalidate
[[headers]]
for = "*.html"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

# Shop pages - conservative caching for better performance 
[[headers]]
for = "/shop/*"
[headers.values]
Cache-Control = "public, max-age=60, s-maxage=180, stale-while-revalidate=600"

# Category pages - PHASE 1: ISR EDGE CACHING
# Let Astro pages set their own Cache-Control headers for ISR
# Cache different filters separately for optimal performance
[[headers]]
for = "/category/*"
[headers.values]
Netlify-Vary = "query=brand,query=availability"

# Product pages - aggressive caching for performance
[[headers]]
for = "/product/*"
[headers.values]
Cache-Control = "public, max-age=60, s-maxage=300, stale-while-revalidate=3600"

# Static assets - long cache with immutable
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Fonts - long cache
[[headers]]
for = "/fonts/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Images - CRITICAL LCP FIX: Aggressive caching with stale-while-revalidate
# Was: max-age=86400 (1 day), s-maxage=604800 (7 days)
# Now: Longer cache + stale-while-revalidate for instant serving
[[headers]]
for = "*.@(jpg|jpeg|png|gif|ico|svg|webp|avif)"
[headers.values]
Cache-Control = "public, max-age=604800, s-maxage=2592000, stale-while-revalidate=86400, immutable"

# Netlify Image CDN - Aggressive caching for transformed images
[[headers]]
for = "/.netlify/images/*"
[headers.values]
Cache-Control = "public, max-age=2592000, s-maxage=31536000, stale-while-revalidate=86400, immutable"

# JS/CSS - long cache with versioning
[[headers]]
for = "*.@(js|css)"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# All other files - security headers and reasonable cache
[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=3600"

# Security Headers
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Content Security Policy - Updated for WordPress images
Content-Security-Policy = "default-src 'self'; img-src 'self' https: data: *.wordpress.com; script-src 'self' 'unsafe-inline' https://sandbox.web.squarecdn.com https://web.squarecdn.com; style-src 'self' 'unsafe-inline'; font-src 'self' https:; connect-src 'self' https: wss:; frame-src 'none'; object-src 'none'"

# Cross-Origin Opener Policy
Cross-Origin-Opener-Policy = "same-origin"

# HSTS
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# SEO
X-Robots-Tag = "index, follow"

[build.environment]
NODE_VERSION = "20"

[dev]
command = "pnpm run dev"
targetPort = 4321
port = 8888
framework = "astro"