[build]
command = "npm run build:only"
publish = "dist"

[build.environment]
NODE_VERSION = "18.20.5"
NODE_OPTIONS = "--max-old-space-size=8192"

[[redirects]]
from = "/*"
to = "/.netlify/functions/entry.mjs"
status = 200
force = true

[[headers]]
for = "/_astro/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[functions]
node_bundler = "esbuild"