# public/admin/config.yml
backend:
  name: git-gateway
  branch: main

site_url: https://elcaminoskateshop.netlify.app
display_url: https://elcaminoskateshop.netlify.app
logo_url: https://elcaminoskateshop.netlify.app/logo.svg

publish_mode: editorial_workflow
media_folder: "public/media"
public_folder: "/media"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Featured Image", name: "featuredImage", widget: "object", fields: [
          {label: "Source", name: "src", widget: "image"},
          {label: "Alt Text", name: "alt", widget: "string", required: false},
          {label: "Caption", name: "caption", widget: "string", required: false}
        ]}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Published Date", name: "publishedDate", widget: "datetime"}
      - {label: "Status", name: "status", widget: "select", options: ["draft", "published"]}
      - {label: "Content", name: "content", widget: "markdown"}
      - {label: "Author", name: "author", widget: "string"}
      - label: "SEO"
        name: "seo"
        widget: "object"
        required: false
        fields:
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Description", name: "description", widget: "text", required: false}
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "No Index", name: "noIndex", widget: "boolean", required: false}

  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "content", widget: "markdown"}
      - label: "Layout"
        name: "layout"
        widget: "list"
        types:
          - label: "Content Block"
            name: "content"
            widget: "object"
            fields:
              - {label: "Block Type", name: "blockType", widget: "hidden", default: "content"}
              - {label: "Content", name: "content", widget: "markdown"}
              - {label: "Appearance", name: "appearance", widget: "select", options: ["normal", "emphasis", "meta"], default: "normal"}
          - label: "Image Gallery"
            name: "imageGallery"
            widget: "object"
            fields:
              - {label: "Block Type", name: "blockType", widget: "hidden", default: "imageGallery"}
              - label: "Images"
                name: "images"
                widget: "list"
                fields:
                  - {label: "Image", name: "src", widget: "image"}
                  - {label: "Alt Text", name: "alt", widget: "string", required: false}
                  - {label: "Caption", name: "caption", widget: "string", required: false}
              - {label: "Columns", name: "columns", widget: "select", options: ["2", "3", "4"], default: "2"}
      - label: "SEO"
        name: "seo"
        widget: "object"
        required: false
        fields:
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Description", name: "description", widget: "text", required: false}
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "No Index", name: "noIndex", widget: "boolean", required: false}