name: Deploy Strapi

on:
  push:
    branches: [master]
    paths:
      - "api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./api/package.json"

      - name: Install dependencies
        run: npm install

      # Create production config directory and file
      - name: Create production config
        run: |
          mkdir -p config/env/production
          cat > config/env/production/server.ts << EOL
          export default ({ env }) => ({
            host: env('HOST', '0.0.0.0'),
            port: env.int('PORT', 1337),
            url: env('PUBLIC_URL'),
            prefix: '/el-camino/api',
            app: {
              keys: env.array('APP_KEYS'),
            },
          });
          EOL

      # Also create middlewares configuration for production
      - name: Create production middlewares config
        run: |
          cat > config/env/production/middlewares.ts << EOL
          export default [
            'strapi::logger',
            'strapi::errors',
            {
              name: 'strapi::security',
              config: {
                contentSecurityPolicy: {
                  directives: {
                    'default-src': ["'self'"],
                    'img-src': ["'self'", 'data:', 'blob:', '*.githubusercontent.com', '*.netlify.app', '*.github.io'],
                    'media-src': ["'self'", 'data:', 'blob:'],
                    'connect-src': ["'self'", 'https:'],
                    'script-src': ["'self'", "'unsafe-inline'", "'unsafe-eval'"],
                    'style-src': ["'self'", "'unsafe-inline'"],
                    'frame-src': ["'self'"],
                  },
                },
              },
            },
            {
              name: 'strapi::cors',
              config: {
                enabled: true,
                origin: ['https://*.netlify.app', 'https://*.github.io'],
                headers: ['*'],
                methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'],
                credentials: true,
              }
            },
            'strapi::poweredBy',
            'strapi::query',
            'strapi::body',
            'strapi::session',
            'strapi::favicon',
            'strapi::public',
          ];
          EOL

      - name: Build Strapi
        run: npm run build
        env:
          NODE_ENV: production
          HOST: "0.0.0.0"
          PORT: 1337
          APP_KEYS: ${{ secrets.STRAPI_APP_KEYS }}
          API_TOKEN_SALT: ${{ secrets.STRAPI_API_TOKEN_SALT }}
          ADMIN_JWT_SECRET: ${{ secrets.STRAPI_ADMIN_JWT_SECRET }}
          JWT_SECRET: ${{ secrets.STRAPI_JWT_SECRET }}
          TRANSFER_TOKEN_SALT: ${{ secrets.STRAPI_TRANSFER_TOKEN_SALT }}
          DATABASE_CLIENT: "sqlite"
          DATABASE_FILENAME: ".tmp/data.db"
          PUBLIC_URL: ${{ secrets.STRAPI_PUBLIC_URL }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./api/build
          enable_jekyll: false
