name: Deploy Strapi

on:
  push:
    branches: [master]
    paths:
      - "api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./api/package.json"

      - name: Install dependencies
        run: npm install

      # Create production config directory and file
      - name: Create production config
        run: |
          mkdir -p config/env/production
          cat > config/env/production/server.ts << EOL
          export default ({ env }) => ({
            host: env('HOST', '0.0.0.0'),
            port: env.int('PORT', 1337),
            url: 'https://travhall.github.io/el-camino/api',
            admin: {
              auth: {
                secret: env('ADMIN_JWT_SECRET'),
              },
            },
            app: {
              keys: env.array('APP_KEYS'),
            },
          });
          EOL

      # Create middleware config for production
      - name: Create middleware config
        run: |
          cat > config/env/production/middlewares.ts << EOL
          export default [
            'strapi::errors',
            {
              name: 'strapi::security',
              config: {
                contentSecurityPolicy: {
                  directives: {
                    'default-src': ["'self'"],
                    'img-src': ["'self'", 'data:', 'blob:', 'https://*.githubusercontent.com', 'https://*.github.io'],
                    'media-src': ["'self'", 'data:', 'blob:'],
                    'script-src': ["'self'", "'unsafe-inline'", "'unsafe-eval'"],
                    'style-src': ["'self'", "'unsafe-inline'"],
                  },
                },
              },
            },
            {
              name: 'strapi::cors',
              config: {
                origin: ['https://travhall.github.io', 'https://*.netlify.app'],
                methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'],
                headers: ['Content-Type', 'Authorization', 'Origin', 'Accept'],
                keepHeaderOnError: true,
              },
            },
            'strapi::poweredBy',
            'strapi::logger',
            'strapi::query',
            'strapi::body',
            'strapi::session',
            'strapi::favicon',
            'strapi::public',
          ];
          EOL

      - name: Build Strapi
        env:
          NODE_ENV: production
          HOST: "0.0.0.0"
          PORT: 1337
          APP_KEYS: ${{ secrets.STRAPI_APP_KEYS }}
          API_TOKEN_SALT: ${{ secrets.STRAPI_API_TOKEN_SALT }}
          ADMIN_JWT_SECRET: ${{ secrets.STRAPI_ADMIN_JWT_SECRET }}
          JWT_SECRET: ${{ secrets.STRAPI_JWT_SECRET }}
          TRANSFER_TOKEN_SALT: ${{ secrets.STRAPI_TRANSFER_TOKEN_SALT }}
          PUBLIC_URL: "https://travhall.github.io/el-camino/api"
        run: |
          npm run build
          # Create the distribution directory
          mkdir -p dist
          # Copy the built admin and API
          cp -r .strapi/client/* dist/
          cp -r public dist/
          # Create redirect index
          cat > dist/index.html << EOL
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>El Camino API</title>
              <script>
                window.location.href = '/el-camino/api/admin';
              </script>
            </head>
            <body>
              <p>Redirecting to admin panel...</p>
            </body>
          </html>
          EOL

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: api/dist
          clean: true
